In [5]:
# Compare events timestamps for raw data vs bids data

from mne_bids import BIDSPath, write_raw_bids, get_anonymization_daysback, read_raw_bids
import random
import pandas as pd
import numpy as np
import itertools
import mne
import os
import sys
import re

fpath = '/project/hcn1/Letty/expectations-ffr/data/raw/sub-3_task-expectations.vhdr'
sub = '3'
task = 'expectations'
run = '1'

RAW_DIR = '../data/raw/' 
MAPS_DIR = '../data/captrak/'
BIDS_DIR = '../data/bids/'

# load data with MNE function for your file format
fpath = os.path.join(RAW_DIR, fpath)
print(fpath)
raw = mne.io.read_raw_brainvision(fpath)
raw.load_data()
raw.set_channel_types({'Aux': 'stim'})

# add some info BIDS will want
print("Add line_freq to raw.info")
raw.info['line_freq'] = 60 # the power line frequency in the building we collected in
raw.add_reference_channels(ref_channels = ['FCz'])

# drop meaningless event name
print("Set annotations")
events, event_ids = mne.events_from_annotations(raw)
events = events[events[:,2] != event_ids['New Segment/'], :]

print('Events for raw data')
print(events)

# shift timestamp
sfreq = raw.info['sfreq']
if sfreq == 10000.0: 
    print(f'Shifting event timings for {sfreq} by 1000 points')
    events[:,0] = events[:,0] + 1000 # Fix timestamp
elif sfreq == 5000.0:
    print(f'Shifting event timings for {sfreq} by 500 points')
    events[:,0] = events[:,0] + 500 # Fix timestamp

print('Shifted events for raw data')
print(events)

# Load bids and events
bids_path = BIDSPath(
    root = BIDS_DIR,
    subject = sub,
    task = task,
    run = run,
    datatype = 'eeg'
    )
print(bids_path)
raw = read_raw_bids(bids_path, verbose = False)
events, event_ids = mne.events_from_annotations(raw)

print('Events for bids data')
print(events)

/project/hcn1/Letty/expectations-ffr/data/raw/sub-3_task-expectations.vhdr
Extracting parameters from /project/hcn1/Letty/expectations-ffr/data/raw/sub-3_task-expectations.vhdr...
Setting channel info structure...


/home/letitiayhho/ipykernel_842527/809981684.py:25: RuntimeWarning: No coordinate information found for channels ['leog', 'reog', 'Aux']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(fpath)
/home/letitiayhho/ipykernel_842527/809981684.py:25: RuntimeWarning: Online software filter detected. Using software filter settings and ignoring hardware values
  raw = mne.io.read_raw_brainvision(fpath)
/home/letitiayhho/ipykernel_842527/809981684.py:25: RuntimeWarning: Not setting positions of 3 misc channels found in montage:
['leog', 'reog', 'Aux']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(fpath)


Reading 0 ... 30437999  =      0.000 ...  3043.800 secs...


/home/letitiayhho/ipykernel_842527/809981684.py:27: RuntimeWarning: The unit for channel(s) Aux has changed from NA to V.
  raw.set_channel_types({'Aux': 'stim'})


Add line_freq to raw.info


/home/letitiayhho/ipykernel_842527/809981684.py:32: RuntimeWarning: The locations of multiple reference channels are ignored.
  raw.add_reference_channels(ref_channels = ['FCz'])


Set annotations
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 41', 'Stimulus/S 42', 'Stimulus/S 43', 'Stimulus/S 51', 'Stimulus/S 52', 'Stimulus/S 53', 'Stimulus/S 61', 'Stimulus/S 62', 'Stimulus/S 63']
Events for raw data
[[  354185        0       53]
 [  360478        0       53]
 [  366612        0       53]
 ...
 [30303803        0       42]
 [30310201        0       41]
 [30316302        0       43]]
Shifting event timings for 10000.0 by 1000 points
Shifted events for raw data
[[  355185        0       53]
 [  361478        0       53]
 [  367612        0       53]
 ...
 [30304803        0       42]
 [30311201        0       41]
 [30317302        0       43]]
../data/bids/sub-3/eeg/sub-3_task-expectations_run-1_eeg.vhdr
Used Annotations descriptions: ['11', '12', '13', '21', '22', '23', '31', '32', '33', '41', '42', 

/home/letitiayhho/ipykernel_842527/809981684.py:63: RuntimeWarning: There are channels without locations (n/a) that are not marked as bad: ['leog', 'reog']
  raw = read_raw_bids(bids_path, verbose = False)
/home/letitiayhho/ipykernel_842527/809981684.py:63: RuntimeWarning: Not setting positions of 2 misc channels found in montage:
['leog', 'reog']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = read_raw_bids(bids_path, verbose = False)
